name: junk

on:
  workflow_dispatch:
    inputs:
      project-choice:
        description: FPGA project
        required: false
        type: choice
        options:
         - Falcon
         - Fiero_C6
         - Fiesta
         - Fiesta1080
         - Fiesta1080SDI
         - Fiesta1080_NoahMed
         - Fiesta5W_SDI
         - Fiesta7Pro
         - Fiesta7WRX
         - FiestaSDI
         - FiestaSDI_C4
         - FiestaWRX
         - FiestaWTX
         - Fiesta_C4
         - Fusion
         - Fiero
         - Fiesta5Pro
         - Fiesta7Pro_KDK"
      project-name:
        description: Your project name
        required: false
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  do-output:
    runs-on: ubuntu-latest
    env:
      OPTION: ${{ inputs.project-choice }}
      NAME: ${{ inputs.project-name }}
    steps:
    - name: Do Output
      run: |
        echo "OPTION: $OPTION"
        echo "NAME: $NAME"

