name: fpga-build

on:
  workflow_dispatch:
    inputs:
      quartus-project:
        description: Quartus project
        required: false
        type: choice
        options:
         - ""
         - Falcon
         - Fiero_C6
         - Fiesta
         - Fiesta1080
         - Fiesta1080SDI
         - Fiesta1080_NoahMed
         - Fiesta5W_SDI
         - Fiesta7Pro
         - Fiesta7WRX
         - FiestaSDI
         - FiestaSDI_C4
         - FiestaWRX
         - FiestaWTX
         - Fiesta_C4
         - Fusion
         - Fiero
         - Fiesta5Pro
         - Fiesta7Pro_KDK
      vivado-project:
        description: Vivado project
        required: false
        type: choice
        options:
         - ""
         - Celica
         - Camaro
         - Camaro_FALD
         - CamaroMax

jobs:
  do-output:
    runs-on: ubuntu-latest
    env:
      QUARTUS: ${{ inputs.quartus-project }}
      VIVADO: ${{ inputs.vivado-project }}
    steps:
    - name: Check options
      run: |
        if [ -n "$QUARTUS" ] && [ -n "$VIVADO" ]
        then
          echo "::error::Multiple projects selected"
          exit 1
        fi
        if [ -z "$QUARTUS" ] && [ -z "$VIVADO" ]
        then
          echo "::error::No project selected"
          exit 1
        fi

    - name: Build Quartus
      if: ${{ inputs.quartus-project != '' }}
      run: |
        echo "QUARTUS: $QUARTUS"

    - name: Build Vivado
      if: ${{ inputs.vivado-project != '' }}
      run: |
        echo "VIVADO: $VIVADO"
